package com.adil.cvscanner.common.api;

public enum ApiErrorCode {

    UPLOAD_NOT_FOUND,

    INVALID_CANDIDATE_QUERY,

    INVALID_PROCESSING_FAILURE_QUERY,

    PROCESSING_LAUNCH_FAILED,

    INVALID_REQUEST_PARAMETER,

    RATE_LIMIT_EXCEEDED,

    RATE_LIMIT_BACKEND_UNAVAILABLE
}